# Generated by Django 4.1.4 on 2023-03-03 16:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description_small', models.CharField(max_length=125)),
                ('Body_desc', ckeditor.fields.RichTextField(null=True)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
                ('Active_check', models.BooleanField()),
            ],
        ),
    ]
